### PR TITLE
:sunglasses:

### PR DESCRIPTION
**Pull request by robbywashere-zz**
Fix for:

https://github.com/hughsk/vinyl-transform/issues/5

### CODE REVIEW

**Comment by jamestalmage** [comment]
Interesting.
Why is it throwing that error event?
Why doesn't it throw using the other methods?

**Comment by robbywashere-zz** [comment]
There are some incompatibilities between gulp's streaming api and browserify's streaming api. The stream is prematurely ended, hence `Error: write after end`

To better understand gulp's streaming api, [take a look at the plugin authorship doc on streams](https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/dealing-with-streams.md)

The reason the gulp-browserify tasks in your gulpfile.js are working is because gulp-browserify is written this way - as the gulp plugin doc specifies.

if you take a look at gulp-browserify's source you will see something like:

`through.obj(function(file, enc, callback) { browserify(...) .... bundle( callback() ) })`

The browserify API offers an optional callback() function argument that can be specified in its .bundle() - this is used together with the `through2` module to continue the processing on 'down the pipeline' when browserify is finished.

When you start off with a browserify stream - `return browserify('./index.coffee')` **VS** gulp.src('app/index.js')  `.bundle()` will return a stream incompatible with gulp streams - so we need to then convert the stream into a vinyl-source-stream, hence `.pipe(source('bundle.js'))`

I think there are some incongruences here because you are also using a browserify transform ... maybe you can take a look at the source ;)

**Comment by jamestalmage** [comment]
Who is ending the stream prematurely? Is there a bug somewhere, or is this just due to the aforementioned api incompatibility.

**Comment by jamestalmage** [comment]
If it's an API incompatibility, why does it only show up when useing a browserify transform?

**Comment by robbywashere-zz** [comment]
Because vinyl-transform does not implement a callback as an argument (which
should be called when browserify's coffee transform is complete inside the .bundle method), being
asynchronous  gulp gets to the end of the processing - ending the stream,
the error is thrown because coffeeify is still attempting to write to the
already closed stream.

Use the through.obj way described, it will save you the headache and give
you more flexibility at the cost of a little more verbosity. I had a
similar problem because I wanted to pass a buffer to browserify rather than
a string representing a file on disk.

I wouldn't call this a bug, its just more of an edge case not compatible
with vinyl-transform.

**Comment by jamestalmage** [comment]
> I wouldn't call this a bug, its just more of an edge case not compatible with vinyl-transform.

Which would be fine if vinyl-transform was not [the recommended way](https://github.com/gulpjs/gulp/blob/master/docs/recipes/browserify-uglify-sourcemap.md) to handle browserify.

**Comment by robbywashere-zz** [comment]
Looking a bit deeper into the code, I think browserify is not handling the
streams correctly when it uses transforms. The exact reason is beyond my
understanding as the code base is quite large and difficult to understand.
I think the discrepancies between streaming api's is that nodes very own
has gone through so many changes. I would be interested to know the exact
reason vinyl-transform and browserify do not work so well together,
especially when using browserify transform plugins.

**Comment by jmm** [comment]
See https://github.com/substack/node-browserify/issues/1044. Long story short, vinyl-transform is designed to wrap a transform (writable) stream. `browserify.bundle()` does not return a stream that's meant to be piped to or written to from outside of browserify.

**Pull request closed without merging**
